"""GitHub Pull Request management."""


from github import Github
from github.GithubException import GithubException


class PRManager:
    """Manages GitHub Pull Requests for content review."""

    PR_TEMPLATE = """## AI Generated Content

**Domain:** {domain}
**Level:** {level}
**Category:** {category}

### Content Information

**Title:** {title}
**Source:** {source_url}
**Credibility Score:** {credibility_score}/10

### Description

{description}

### Review Checklist

- [ ] Content is accurate and well-written
- [ ] Appropriate for target audience level
- [ ] Sources are credible and properly cited
- [ ] No plagiarism or copyright issues
- [ ] Metadata (tags, category) is correct
- [ ] Formatting is correct

### Tags

{tags}

---

*This content was automatically generated by the knowledge-base-agent.*
*Review the content carefully before merging.*
"""

    def __init__(self, github_token: str, owner: str, repo: str):
        """Initialize PR manager.

        Args:
            github_token: GitHub API token
            owner: Repository owner
            repo: Repository name
        """
        self.client = Github(github_token)
        self.repo = self.client.get_repo(f"{owner}/{repo}")
        self.owner = owner
        self.repo_name = repo

    def create_pr(
        self,
        title: str,
        body: str,
        head_branch: str,
        base_branch: str = "main",
        labels: list[str] | None = None,
        reviewers: list[str] | None = None,
    ) -> int:
        """Create a pull request.

        Args:
            title: PR title
            body: PR description
            head_branch: Source branch
            base_branch: Target branch
            labels: List of label names
            reviewers: List of reviewer usernames

        Returns:
            PR number

        Raises:
            GithubException: If PR creation fails
        """
        try:
            # Create PR
            pr = self.repo.create_pull(
                title=title, body=body, head=head_branch, base=base_branch
            )

            # Add labels
            if labels:
                pr.add_to_labels(*labels)

            # Request reviewers
            if reviewers:
                # Remove @ prefix if present
                reviewer_list = [r.lstrip("@") for r in reviewers]
                try:
                    pr.create_review_request(reviewers=reviewer_list)
                except GithubException as e:
                    # Ignore reviewer errors (they may not have access)
                    print(f"Could not add reviewers: {e}")

            return pr.number

        except GithubException:
            raise

    def create_content_pr(
        self,
        branch_name: str,
        content_metadata: dict,
        labels: list[str] | None = None,
        reviewers: list[str] | None = None,
    ) -> int:
        """Create PR for AI-generated content.

        Args:
            branch_name: Branch containing content
            content_metadata: Dict with content information
            labels: List of label names
            reviewers: List of reviewer usernames

        Returns:
            PR number
        """
        # Build PR title
        title = f"[AI Generated] {content_metadata['title']}"

        # Build PR body from template
        tags_str = ", ".join(content_metadata.get("tags", []))
        body = self.PR_TEMPLATE.format(
            domain=content_metadata.get("domain", "unknown"),
            level=content_metadata.get("level", "unknown"),
            category=content_metadata.get("category", "unknown"),
            title=content_metadata["title"],
            source_url=content_metadata.get("source_url", "N/A"),
            credibility_score=content_metadata.get("credibility_score", 0),
            description=content_metadata.get("description", "No description provided."),
            tags=tags_str,
        )

        # Add default labels
        default_labels = ["ai-generated", "needs-review"]
        if labels:
            default_labels.extend(labels)

        # Add domain as label
        if "domain" in content_metadata:
            default_labels.append(content_metadata["domain"])

        return self.create_pr(
            title=title,
            body=body,
            head_branch=branch_name,
            base_branch="main",
            labels=default_labels,
            reviewers=reviewers,
        )

    def get_pr(self, pr_number: int):
        """Get pull request by number.

        Args:
            pr_number: PR number

        Returns:
            PullRequest object

        Raises:
            GithubException: If PR not found
        """
        return self.repo.get_pull(pr_number)

    def close_pr(self, pr_number: int, comment: str | None = None) -> bool:
        """Close a pull request.

        Args:
            pr_number: PR number
            comment: Optional comment to add

        Returns:
            True if closed successfully

        Raises:
            GithubException: If close fails
        """
        try:
            pr = self.get_pr(pr_number)

            # Add comment if provided
            if comment:
                pr.create_issue_comment(comment)

            # Close PR
            pr.edit(state="closed")

            return True
        except GithubException:
            raise

    def merge_pr(
        self,
        pr_number: int,
        merge_method: str = "squash",
        commit_message: str | None = None,
    ) -> bool:
        """Merge a pull request.

        Args:
            pr_number: PR number
            merge_method: Merge method (merge, squash, rebase)
            commit_message: Optional custom commit message

        Returns:
            True if merged successfully

        Raises:
            GithubException: If merge fails
        """
        try:
            pr = self.get_pr(pr_number)

            # Merge PR
            pr.merge(merge_method=merge_method, commit_message=commit_message)

            return True
        except GithubException:
            raise

    def list_open_prs(self, labels: list[str] | None = None) -> list:
        """List open pull requests.

        Args:
            labels: Filter by labels

        Returns:
            List of PullRequest objects
        """
        pulls = self.repo.get_pulls(state="open")

        if labels:
            # Filter by labels
            filtered = []
            for pr in pulls:
                pr_labels = [label.name for label in pr.labels]
                if any(label in pr_labels for label in labels):
                    filtered.append(pr)
            return filtered

        return list(pulls)
